export const SAGA_LOGIN_REQUEST = "SAGA_LOGIN_REQUEST";
export const USER_CONNECTION_CHECK = "USER_CONNECTION_CHECK";
export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const USER_CHECK_REQUEST = "USER_CHECK_REQUEST";

export const REDUX_SET_USERDATA = "REDUX_SET_USERDATA";
export const REDUX_USER_LOGOUT =" REDUX_SET_LOGOUT"

export const TOAST_MESSAGE_REQUEST = "TOAST_MESSAGE_REQUEST"