export const SAGA_LOGIN_REQUEST = "SAGA_LOGIN_REQUEST";
export const SAGA_USER_CHECK = "SAGA_USER_CHECK";
export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";

export const REDUX_SET_USERDATA = "REDUX_SET_USERDATA";
export const REDUX_SET_LOGOUT =" REDUX_SET_LOGOUT"